Update mworkcnc.in

diff --git a/scripts/mworkcnc.in b/scripts/mworkcnc.in
--- a/scripts/mworkcnc.in
+++ b/scripts/mworkcnc.in
@@ -22,6 +22,11 @@ if test "xyes" = "x@RUN_IN_PLACE@"; then
     fi
 fi
 
+# Force pyopengl (python3-opengl) to use its GLX backend, even
+# if we're running on Wayland where it would normally use EGL.
+if [[ ! -v LINUXCNC_OPENGL_PLATFORM || "${LINUXCNC_OPENGL_PLATFORM}" == "glx" ]]; then
+    export PYOPENGL_PLATFORM="x11"
+fi															  
 ################################################################################
 # 0. Values that come from configure
 ################################################################################
@@ -101,26 +106,26 @@ Usage:
     This help
 
   $ $P [Options]
-    Choose the configuration inifile graphically
+    Choose the configuration INI file graphically
 
   $ $P [Options] path/to/your_ini_file
-    Name the configuration inifile using its path
+    Name the configuration INI file using its path
 
   $ $P [Options] -l
-    Use the previously used configuration inifile
+    Use the previously used configuration INI file
 
 Options:
     -d: Turn on "debug" mode
     -v: Turn on "verbose" mode
-    -k: Continue in the presence of errors in .hal files
+    -k: Continue in the presence of errors in HAL files
     -t "tpmodulename [parameters]"
             specify custom trajectory_planning_module
             overrides optional ini setting [TRAJ]TPMOD
     -m "homemodulename [parameters]"
             specify custom homing_module
-            overrides optional ini setting [EMCMOT]HOMEMOD
-    -H "dirname": search dirname for Halfiles before searching
-                  ini directory and system library:
+            overrides optional INI setting [EMCMOT]HOMEMOD
+    -H "dirname": search dirname for HAL files before searching
+                  INI directory and system library:
                   $HALLIB_DIR
 Note:
     The -H "dirname" option may be specified multiple times
@@ -133,29 +138,30 @@ EOF
 ################################################################################
 while getopts "dvlhkrH:t:m:" opt
 do
-	case "$opt" in
-	d)
-		# enable echoing of script and command output
-		if tty -s; then
-		    DEBUG_FILE=/dev/fd/2
-		    echo "Debug mode on" >$DEBUG_FILE
-		fi
-		set -x;;
-	v)
-		# enable printing of verbose messages
-		if tty -s; then
-		    PRINT_FILE=/dev/fd/1
-		    echo "Verbose mode on" >$PRINT_FILE
-		fi;;
-        r)
-                RUNTESTS=yes
-                ;;
-	l)
-		USE_LAST_INIFILE=1;;
-        k)      DASHK=-k;;
-	h)
-		usage
-		exit 0;;
+    case "$opt" in
+    d)
+        # enable echoing of script and command output
+        if tty -s; then
+            DEBUG_FILE=/dev/fd/2
+            echo "Debug mode on" >$DEBUG_FILE
+        fi
+        set -x;;
+    v)
+        # enable printing of verbose messages
+        if tty -s; then
+            PRINT_FILE=/dev/fd/1
+            echo "Verbose mode on" >$PRINT_FILE
+        fi;;
+    r)
+        RUNTESTS=yes
+        ;;
+    l)
+        USE_LAST_INIFILE=1;;
+    k)
+        DASHK=-k;;
+    h)
+        usage
+        exit 0;;
     H)  # -H dirname: prepend dirname to HALLIB_PATH
         if [ -d $OPTARG ]; then
             HALLIB_PATH=$(cd $OPTARG;pwd):$HALLIB_PATH
@@ -175,10 +181,10 @@ do
         # and be located in: $LINUXCNC_RTLIB_DIR
         HOMEMOD=$OPTARG
         ;;
-	*)
-		usage
-		exit 1
-	esac
+    *)
+        usage
+        exit 1
+    esac
 done
 shift $(($OPTIND-1))
 
@@ -248,7 +254,7 @@ as well as in the output of the shell command 'dmesg' and in the terminal"
 trap ErrorCheck EXIT
 
 ################################################################################
-# 1.3. INIFILE                           find inifile to use                   #
+# 1.3. INIFILE                           find INI file to use                   #
 ################################################################################
 
 if [ ! -z "$1" ]; then
@@ -295,10 +301,10 @@ export LINUXCNC_NCFILES_DIR
 
 [ -z $RUNTESTS ] && echo "LINUXCNC - $LINUXCNCVERSION" 
 
-# was an inifile specified on the command line?
+# was an INI file specified on the command line?
 if [ ! -z "$USE_LAST_INIFILE" ]; then
     INIFILE=$($INIVAR -ini ~/.linuxcncrc -var LAST_CONFIG -sec PICKCONFIG 2>>$DEBUG_FILE)
-    echo "Using previous inifile: $INIFILE" >> $PRINT_FILE
+    echo "Using previous INI file: $INIFILE" >> $PRINT_FILE
 fi
 
 if [ ! -n "$INIFILE" ] ; then
@@ -384,7 +390,7 @@ function run_applications () {
        case "$app_name" in
          /*) # absolute pathname
              exe_name=$app_name;;
-       \./*) # name relative to inifile directory
+       \./*) # name relative to INI file directory
              exe_name="$(pwd)/$app_name";;
           *) # try local first then PATH
              exe_name=$(pwd)/$app_name
@@ -419,18 +425,18 @@ export PATH=$CONFIG_DIR/bin:$PATH
 [ -z $RUNTESTS ] && echo "Machine configuration directory is '$INI_DIR'"
 echo "Machine configuration file is '$INI_NAME'"
 
-# make sure ini file exists (the tcl script just did this, so we could 
+# make sure INI file exists (the tcl script just did this, so we could 
 # eliminate this test, but it does no harm)
 
 if [ ! -f "$INIFILE" ] ; then
-    echo "Could not find ini file '$INIFILE'"
+    echo "Could not find INI file '$INIFILE'"
     trap '' EXIT
     exit -1
 fi
 echo INIFILE="$INIFILE" >>$PRINT_FILE
 
 ################################################################################
-# 2.  extract info from the ini file that we will need later
+# 2.  extract info from the INI file that we will need later
 ################################################################################
 retval=
 
@@ -475,7 +481,7 @@ function GetFromIniEx {
 GetFromIni VERSION EMC
 if [ "$retval" != "1.1" ]; then
     if [ -z "$DISPLAY" ]; then
-        echo "ini file [EMC]VERSION indicates update is needed, but the update GUI can't run without an X display"
+        echo "INI file [EMC]VERSION indicates update is needed, but the update GUI can't run without an X display"
         exit 1
     fi
     update_ini -d "$INIFILE"
@@ -516,12 +522,12 @@ RS274NGC_PARAMFILE=$retval
 GetFromIniEx MOT MOT EMCMOT EMCMOT motmod
 EMCMOT=$retval$MODULE_EXT # add module extension
 
-# commandline -t option supersedes inifile setting
+# commandline -t option supersedes INI file setting
 if [ -z "$TPMOD" ] ; then
     GetFromIniQuiet TPMOD   TRAJ
     TPMOD=${retval:-tpmod} #use default if not found
 fi
-# commandline -m option supersedes inifile setting
+# commandline -m option supersedes INI file setting
 if [ -z "$HOMEMOD" ] ; then
     GetFromIniQuiet HOMEMOD EMCMOT
     HOMEMOD=${retval:-homemod} #use default if not found
@@ -797,7 +803,7 @@ echo Starting LinuxCNC...
 # trap ^C so that it's called if user interrupts script
 trap 'Cleanup ; exit 0' SIGINT SIGTERM
 
-# go to the dir where the ini file is
+# go to the dir where the INI file is
 # either configs/<specific-config> when run-in-place, or
 # /usr/local/share/linuxcnc/configs/<specific-config> (wherever it was installed)
 cd "$INI_DIR"
@@ -900,7 +906,7 @@ if [ -n "$TWOPASS" ] ; then
   fi
 else
     # 4.3.6.2. conventional execution of  HALCMD config files
-    # get first config file name from ini file
+    # get first config file name from INI file
     NUM=1
     CFGFILE=`$INIVAR -tildeexpand -ini "$INIFILE" -var HALFILE -sec HAL -num $NUM 2> /dev/null`
     while [ -n "$CFGFILE" ] ; do
@@ -959,7 +965,7 @@ else
                 exit -1
             fi
         esac
-        # get next config file name from ini file
+        # get next config file name from INI file
         NUM=$(($NUM+1))
         CFGFILE=`$INIVAR -tildeexpand -ini "$INIFILE" -var HALFILE -sec HAL -num $NUM 2> /dev/null`
     done
@@ -976,8 +982,8 @@ fi
 
 halcmd loadusr -Wn inihal $EMCTASK -ini "$INIFILE" &
 
-# 4.3.8. execute discrete HAL commands from ini file (if any)
-# get first command from ini file
+# 4.3.8. execute discrete HAL commands from INI file (if any)
+# get first command from INI file
 NUM=1
 HALCOMMAND=`$INIVAR -ini "$INIFILE" -var HALCMD -sec HAL -num $NUM 2> /dev/null`
 while [ -n "$HALCOMMAND" ] ; do
